### ISSUE TITLE
【MacOS】Crash in debug mode

### ISSUE THREAD

**Issue by beijie001** [TerminalStudio/pty#8]
When the child process run unix.execve(executable.toNativeUtf8(), argv, env)  ,the child process will crash,return 11.
And It's OK in Release mode.

Add stacktrace:

===== CRASH =====
si_signo=Segmentation fault: 11(11), si_code=1, si_addr=0x10fd8551b
version=2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_x64"
pid=75053, thread=5891, isolate_group=main(0x7ff31b01b800), isolate=main(0x7ff31b020200)
isolate_instructions=10d934580, vm_instructions=10d934580
  pc 0x000000010fd8551b fp 0x00007000034b65d0 Unknown symbol
  pc 0x0000000114eafb27 fp 0x00007000034b6618 Unknown symbol
  pc 0x0000000114ea1911 fp 0x00007000034b6718 Unknown symbol
  pc 0x0000000114ea01b9 fp 0x00007000034b67c0 Unknown symbol
  pc 0x0000000114e9eef6 fp 0x00007000034b6850 Unknown symbol
  pc 0x0000000114e9e2ee fp 0x00007000034b6888 Unknown symbol
  pc 0x0000000114e9df49 fp 0x00007000034b68b0 Unknown symbol
  pc 0x0000000114e9de7b fp 0x00007000034b6908 Unknown symbol
  pc 0x0000000114e9ce8d fp 0x00007000034b6938 Unknown symbol
  pc 0x0000000114e9cc1e fp 0x00007000034b6998 Unknown symbol
  pc 0x0000000114e9c5f8 fp 0x00007000034b69d0 Unknown symbol
  pc 0x000000010fd825af fp 0x00007000034b6a48 Unknown symbol
  pc 0x000000010dae4052 fp 0x00007000034b6ae0 dart::DartEntry::InvokeCode(dart::Code const&, dart::Array const&, dart::Array const&, dart::Thread*)+0x112
  pc 0x000000010dae3e55 fp 0x00007000034b6b50 dart::DartEntry::InvokeFunction(dart::Function const&, dart::Array const&, dart::Array const&, unsigned long)+0x155
  pc 0x000000010dae69ef fp 0x00007000034b6bb0 dart::DartLibraryCalls::HandleMessage(dart::Object const&, dart::Instance const&)+0x1df
  pc 0x000000010db0da23 fp 0x00007000034b6db0 dart::IsolateMessageHandler::HandleMessage(std::__1::unique_ptr<dart::Message, std::__1::default_delete<dart::Message> >)+0x4f3

  pc 0x000000010db3f1a4 fp 0x00007000034b6e30 dart::MessageHandler::HandleMessages(dart::MonitorLocker*, bool, bool)+0x144
  pc 0x000000010db3f7c9 fp 0x00007000034b6e90 dart::MessageHandler::TaskCallback()+0x1e9
  pc 0x000000010dc74ce8 fp 0x00007000034b6f20 dart::ThreadPool::WorkerLoop(dart::ThreadPool::Worker*)+0x158
  pc 0x000000010dc74faf fp 0x00007000034b6f50 dart::ThreadPool::Worker::Main(unsigned long)+0x6f
  pc 0x000000010dbd7605 fp 0x00007000034b6fb0 dart::ThreadStart(void*)+0xb5
  pc 0x00007fff6b4fe109 fp 0x00007000034b6fd0 _pthread_start+0x94
  pc 0x00007fff6b4f9b8b fp 0x00007000034b6ff0 thread_start+0xf
-- End of DumpStackTrace

**Comment by xtyxtyx** [comment]
Thanks for reporting the issue. Could you provide your `flutter doctor` or `dart --version`?

BTW this looks like a FFI related issue which is usually hard to address. This package currently is only known to work well in flutter release mode.

I've submitted [a patch](https://github.com/dart-lang/sdk/issues/23165#issuecomment-835970541) that adds pty functionalities to dart itself and is expected to work much better. It will be available once the patch is merged.

**Comment by beijie001** [comment]
> Thanks for reporting the issue. Could you provide your `flutter doctor` or `dart --version`?
> 
> BTW this looks like a FFI related issue which is usually hard to address. This package currently is only known to work well in flutter release mode.
> 
> I've submitted [a patch](https://github.com/dart-lang/sdk/issues/23165#issuecomment-835970541) that adds pty functionalities to dart itself and is expected to work much better. It will be available once the patch is merged.

Thanks your reply.
I test more, it work well only when i  compile with dart aot.
I report the issure, because the readme of project  show me that it work well on macos in debug mode. Maybe I have something wrong.    

➜  flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.1, on Mac OS X 10.15.7 19H2 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2020.1.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (3 available)

➜  dart --version
Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_x64"

**Comment by beijie001** [comment]
After update the macos version, it works well in debug mode.
